# Generated by Django 5.2.8 on 2025-11-13 06:40

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IronTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('priority', models.IntegerField(db_index=True, default=0)),
                ('scheduled_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=5)),
                ('last_error', models.TextField(blank=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('locked_by', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'iron_task',
                'ordering': ['-priority', 'scheduled_at'],
                'indexes': [models.Index(fields=['status', 'scheduled_at'], name='iron_task_status_9035ef_idx'), models.Index(fields=['status', 'priority'], name='iron_task_status_df0c83_idx')],
            },
        ),
        migrations.CreateModel(
            name='IronWebhookDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event', models.CharField(db_index=True, max_length=255)),
                ('target_url', models.URLField()),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('success', 'Success'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=5)),
                ('last_response_code', models.IntegerField(blank=True, null=True)),
                ('last_response_body', models.TextField(blank=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'iron_webhook_delivery',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event', 'status'], name='iron_webhoo_event_a8d48b_idx')],
            },
        ),
        migrations.CreateModel(
            name='IronIncomingWebhook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(help_text='Например: stripe, github, custom', max_length=100)),
                ('event', models.CharField(blank=True, max_length=255)),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('received', 'Received'), ('handled', 'Handled'), ('failed', 'Failed')], db_index=True, default='received', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('handler_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_webhooks', to='core.irontask')),
            ],
            options={
                'db_table': 'iron_incoming_webhook',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['source', 'status'], name='iron_incomi_source_a3dbd5_idx')],
            },
        ),
    ]
